### ISSUE TITLE
#TODO - Multilingualism, Likes and more

### ISSUE THREAD

**Issue by waydk** [waydk/flask_blog#10]
- [ ] Add multilingualism to articles
- [ ] Add the ability to comment and like
- [ ] Add a custom cursor
